(function(){
const M=window.TrainingModel,C=window.TrainingCharts;const $=id=>document.getElementById(id);let saved=[],structureSlopePct=M.C.structureGroundSlopePct;
function fmtNum(v,d=0){return v.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d})}
function getParams(){return{depth:+$('channelDepth').value,width:+$('floodplainWidth').value,slopePct:M.C.benchSlopePct,structureSlopePct}}
function setParams(p){$('channelDepth').value=p.depth;$('floodplainWidth').value=p.width;render()}
function interpretation(r){const capture=r.existingEAD>0?100*(r.existingEAD-r.ead)/r.existingEAD:0;if(r.cost<1)return 'This is the existing, no-project section. Reduce the remaining channel depth to begin excavating an alternative.';let msg=`This alternative removes about <strong>${capture.toFixed(0)}%</strong> of expected annual damage for a conceptual cost of <strong>${C.money(r.cost)}</strong>. `;if(r.cost<500000&&capture<10)msg+='It is doing something hydraulically, but not enough to materially change the damage problem.';else if(capture>85&&r.bcr<1)msg+='It removes most of the modeled damage, but the additional excavation is expensive relative to the remaining benefit.';else msg+='Save it, then test both a smaller and a larger section. The teaching point is the change in slope between successive saved points.';return msg}
function scenario(r){return{cost:r.cost,npvBenefit:r.npvBenefit,bcr:r.bcr,params:{...r.params}}}
function render(){const p=getParams(),r=M.evaluate(p);$('depthOut').textContent=p.depth.toFixed(2)+' ft';$('widthOut').textContent=p.width.toFixed(0)+' ft';$('slopeOut').textContent=p.slopePct.toFixed(2)+'%';$('excavationMetric').textContent=fmtNum(r.excavationCY/1000,0)+'k CY';$('costMetric').textContent=C.money(r.cost);$('capacityMetric').textContent=r.capacity.label;$('benefitMetric').textContent=C.money(r.npvBenefit);$('bcrMetric').textContent=r.bcr.toFixed(2);const eventIdx=M.C.events.indexOf(+$('waterEvent').value);C.section($('sectionChart'),r,eventIdx);C.losses($('lossChart'),r);C.benefit($('benefitChart'),saved,r);$('eventTable').innerHTML=M.C.events.map((ev,i)=>`<tr><td>${ev}-yr</td><td>${fmtNum(M.C.flows[i])} cfs</td><td>${C.money(r.existingDamages[i])}</td><td>${C.money(r.damages[i])}</td><td>${C.money(Math.max(r.existingDamages[i]-r.damages[i],0))}</td></tr>`).join('');$('interpretation').innerHTML=interpretation(r);window.currentResult=r}
['channelDepth','floodplainWidth','waterEvent'].forEach(id=>$(id).addEventListener('input',render));
$('saveScenario').addEventListener('click',()=>{saved.push(scenario(window.currentResult));saved=saved.sort((a,b)=>a.cost-b.cost);render()});
$('resetScenarios').addEventListener('click',()=>{saved=[];render()});
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.preset==='tiny')setParams({depth:3.75,width:90});else setParams({depth:.25,width:95})}));
document.querySelectorAll('[data-structure-slope]').forEach(b=>b.addEventListener('click',()=>{structureSlopePct=+b.dataset.structureSlope;document.querySelectorAll('[data-structure-slope]').forEach(button=>{const active=button===b;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active)});saved=saved.map(s=>scenario(M.evaluate({...s.params,structureSlopePct}))).sort((a,b)=>a.cost-b.cost);render()}));
render();
})();
